Create T012_M3_batch_ui.py
InochiFumetsu/district_12 pull request #93
Opened 2022-12-09 00:47 UTC by Hey1121

#10

2022-12-09 05:50 UTC, InochiFumetsu requested changes
You need to upload the batch file too!

2022-12-09 14:00 UTC, Jackinator27 approved these changes

2022-12-10 16:23 UTC, InochiFumetsu commented on T012_M3_batch_ui.py
> +    print("Please input the name of file where the commands are sotred")
```suggestion
    print("Please input the name of file where the commands are stored")
```

2022-12-10 16:49 UTC, InochiFumetsu commented on T012_M3_batch_ui.py
> +                command_list[1], loaded_data)
```suggestion
                loaded_data, command_list[1])
```

2022-12-10 16:51 UTC, InochiFumetsu requested changes
The second code suggestion needs to go through (the profs said the dict/att arguments for the optimization functions could go either way but was supposed to be <dict>, <attr> (so I swapped them around in my code))

2022-12-10 16:53 UTC, InochiFumetsu commented on T012_M3_batch_ui.py
> +            elif command_list[2] == 'N':
I didn't read the function / module requirements for your guys' code -- but I notice you don't accept lower-case 'y' or 'n' (or 'yes' or 'no' or 'yEs' etc.) -- does that matter or?

2022-12-10 16:59 UTC, InochiFumetsu approved these changes

2022-12-10 17:02 UTC, InochiFumetsu commented on T012_M3_batch_ui.py
> +                print(sorted_data)
```suggestion
                for i in iter(sorted_data):
                    print(i, ":", sep="")
                    for j in range(len(sorted_data[i])):
                        print("\t", sorted_data[i][j], sep="")
```

2022-12-10 17:03 UTC, InochiFumetsu commented on T012_M3_batch_ui.py
> +                print(sorted_data)
not important -- same suggestion I made to Jack -- just displays nicer. Try it in your local version, see if you like.

2022-12-10 17:40 UTC, InochiFumetsu commented on T012_M3_batch_ui.py
> +                  command_list[1], "is", max_result)
```suggestion
                  command_list[1], "is", max_result)
          file_contents.close()
```

2022-12-11 17:37 UTC, Jackinator27 approved these changes

2022-12-11 19:35 UTC, InochiFumetsu approved these changes

2022-12-11 20:58 UTC, InochiFumetsu approved these changes

2022-12-11 20:59 UTC, Jackinator27 approved these changes

2022-12-11 20:59 UTC, MilanxDjordjevic approved these changes

2022-12-11 20:59 UTC, merged